<?php
/**
 * Copyright © 2018 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 * @var $block Mollie\Payment\Block\Adminhtml\Render\Header
 */
?>
<div class="mm-block-teknepay">
    <a class="helpbutton" href="http://teknepay.com/#" target="_blank"></a>
    <p>
        <strong>Developed by Teknepay.</strong>
        <br /><br />
        Teknepay will provide your business with flexible rates that will improve as your revenue increases. <br /> We will get you set up within 24 hours, have excellent customer service and support, and work with a large variety of verticals facing cash flow problems.
    </p>
    <table>
        <tbody>
        <tr>
            <td>
                <div class="icon1"></div>
                <a href="http://teknepay.com/#contact" target="_blank">Get an Account</a>
            </td>
            <td>
                <div class="icon2"></div>
                <a href="mailto:support@teknepay.com" target="_blank">Get Support</a>
            </td>
			<td>
                <div class="icon3"></div>
                <a href="http://teknepay.com/#contact" target="_blank">Contact Us</a>
            </td>
        </tr>
        </tbody>
    </table>
</div>